owner: hada-io
repo: upptime
user-agent: KojBot
sites:
  - name: GeekNews - https://news.hada.io
    url: https://news.hada.io
  - name: Write - https://write.hada.io
    url: https://write.hada.io
  - name: Hada - https://hada.io
    url: https://hada.io
notifications:
  - type: slack
    channel: CUSH0EN2U
assignees:
  - xguru
status-website:
  cname: upptime.hada.io
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: Upptime
  introTitle: "**Upptime** for Hada"
  introMessage: Hada가 만드는 서비스들의 현재 상태입니다. GitHub Actions 를 이용한 Upptime 으로 운영되고 있습니다.
